# This version must match the MAKE_DC_VERSION value below
#version: "3.7"

volumes:
  pgdata:

networks:
  postgres:
    driver: bridge

services:
  postgres:
    image: "${POSTGIS_IMAGE:-openmaptiles/postgis}:${TOOLS_VERSION}"
    #command: postgres -c "config_file=./etc/postgresql/postgresql.conf"
    command: postgres -c "shared_buffers=16GB" -c "autovacuum=on" -c "work_mem=1500MB" -c "maintenance_work_mem=4096kB" -c "effective_cache_size=20GB" -c "random_page_cost=1.1" -c "effective_cache_size=40GB" -c "dynamic_shared_memory_type=posix" -c "max_wal_size=1GB" -c "min_wal_size=80MB" -c "wal_buffers=16MB" -c "effective_io_concurrency=30" -c "max_connections=300"
    # Use "command: postgres -c jit=off" for PostgreSQL 11+ because of slow large MVT query processing
    # Use "shm_size: 512m" if you want to prevent a possible 'No space left on device' during 'make generate-tiles-pg'
    shm_size: 3g
    volumes:
      - pgdata:/var/lib/postgresql/data
      #- ./etc/postgresql/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    networks:
      - postgres
    ports:
      - "${PGPORT:-5432}:${PGPORT:-5432}"
    env_file: .env
    environment:
      # postgress container uses old variable names
      POSTGRES_DB: ${PGDATABASE:-openmaptiles}
      POSTGRES_USER: ${PGUSER:-openmaptiles}
      POSTGRES_PASSWORD: ${PGPASSWORD:-openmaptiles}
      PGPORT: ${PGPORT:-5432}
      #TILE_TIMEOUT: 3600000

  import-data:
    image: "openmaptiles/import-data:${TOOLS_VERSION}"
    env_file: .env
    networks:
      - postgres

  openmaptiles-tools: &openmaptiles-tools
    image: "openmaptiles/openmaptiles-tools:${TOOLS_VERSION}"
    env_file: .env
    environment:
      # Must match the version of this file (first line)
      # download-osm will use it when generating a composer file
      MAKE_DC_VERSION: "3.7"
      # Allow DIFF_MODE, MIN_ZOOM, and MAX_ZOOM to be overwritten from shell
      DIFF_MODE: ${DIFF_MODE}
      MIN_ZOOM: ${MIN_ZOOM}
      MAX_ZOOM: ${MAX_ZOOM}
      #Provide BBOX from *.bbox file if exists, else from .env
      BBOX: ${BBOX}
      # Imposm configuration file describes how to load updates when enabled
      IMPOSM_CONFIG_FILE: ${IMPOSM_CONFIG_FILE}
      # Control import-sql processes
      MAX_PARALLEL_PSQL: ${MAX_PARALLEL_PSQL}
      PGDATABASE: ${PGDATABASE:-openmaptiles}
      PGUSER: ${PGUSER:-openmaptiles}
      PGPASSWORD: ${PGPASSWORD:-openmaptiles}
      PGPORT: ${PGPORT:-5432}
      MBTILES_FILE: ${MBTILES_FILE}
      #UV_THREADPOOL_SIZE:
    networks:
      - postgres
    volumes:
      - .:/tileset
      - ./data:/import
      - ./data:/export
      - ./build/sql:/sql
      - ./build:/mapping
      - ./cache:/cache
      - ./style:/style

  update-osm:
    <<: *openmaptiles-tools
    command: import-update

  generate-changed-vectortiles:
    image: "openmaptiles/generate-vectortiles:${TOOLS_VERSION}"
    command: ./export-list.sh
    volumes:
      - ./data:/export
      - ./build/openmaptiles.tm2source:/tm2source
    networks:
      - postgres
    env_file: .env
    environment:
      MBTILES_NAME: ${MBTILES_FILE}
      # Control tilelive-copy threads
      COPY_CONCURRENCY: ${COPY_CONCURRENCY}
      PGDATABASE: ${PGDATABASE:-openmaptiles}
      PGUSER: ${PGUSER:-openmaptiles}
      PGPASSWORD: ${PGPASSWORD:-openmaptiles}
      PGPORT: ${PGPORT:-5432}

  generate-vectortiles:
    image: "openmaptiles/generate-vectortiles:${TOOLS_VERSION}"
    volumes:
      - ./data:/export
      - ./build/openmaptiles.tm2source:/tm2source
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 16000000000 # ~16gb
      - postgres
    env_file: .env
    environment:
      MBTILES_NAME: ${MBTILES_FILE}
      BBOX: ${BBOX}
      MIN_ZOOM: ${MIN_ZOOM}
      MAX_ZOOM: ${MAX_ZOOM}
      # Control tilelive-copy threads
      COPY_CONCURRENCY: ${COPY_CONCURRENCY}
      #
      PGDATABASE: ${PGDATABASE:-openmaptiles}
      PGUSER: ${PGUSER:-openmaptiles}
      PGPASSWORD: ${PGPASSWORD:-openmaptiles}
      PGPORT: ${PGPORT:-5432}
      #UV_THREADPOOL_SIZE: ${UV_THREADPOOL_SIZE}

  postserve:
    image: "openmaptiles/openmaptiles-tools:${TOOLS_VERSION}"
    command: "postserve ${TILESET_FILE} --verbose --serve=${OMT_HOST:-http://localhost}:${PPORT:-8090}"
    env_file: .env
    environment:
      TILESET_FILE: ${TILESET_FILE}
    networks:
      - postgres
    ports:
      - "${PPORT:-8090}:${PPORT:-8090}"
    volumes:
      - .:/tileset
      #- ./etc/postgresql/postgresql.conf:/var/lib/postgresql/data/postgresql.conf

  maputnik_editor:
    image: "maputnik/editor"
    ports:
      - "8088:8888"

  tileserver-gl:
    image: "maptiler/tileserver-gl:latest"
    command:
      - --port
      - "${TPORT:-8080}"
      - --config
      - "/style/config.json"
    ports:
      - "${TPORT:-8080}:${TPORT:-8080}"
    volumes:
      - ./data:/data
      - ./style:/style
      - ./build:/build
