version: "2"
volumes:
  pgdata:
services:
  postgres:
    image: "openmaptiles/postgis:2.3"
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
     - "5432"
    env_file: .env
  import-natural-earth:
    image: "openmaptiles/import-natural-earth:1.0"
    env_file: .env
    links:
    - postgres
  import-water:
    image: "openmaptiles/import-water:0.2"
    env_file: .env
    links:
    - postgres
  import-lakelines:
    image: "openmaptiles/import-lakelines:0.9"
    env_file: .env
    links:
    - postgres
  import-osm:
    image: "openmaptiles/import-osm:0.1"
    env_file: .env
    environment:
      DIFF_MODE: "false"
    links:
    - postgres
    volumes:
     - ./data:/import
     - ./build:/mapping
  import-sql:
    image: "openmaptiles/import-sql:0.1"
    env_file: .env
    links:
    - postgres
    volumes:
     - ./build:/sql
  mapbox-studio:
    image: "osm2vectortiles/mapbox-studio"
    volumes:
     - ./build/openmaptiles.tm2source:/projects/openmaptiles.tm2source
    links:
     - postgres:db
    ports:
     - "3000:3000"
  generate-vectortiles:
    image: "openmaptiles/generate-vectortiles:0.1"
    volumes:
    - ./data:/export
    - ./build/openmaptiles.tm2source:/tm2source
    links:
    - postgres:postgres
    env_file: .env
    environment:
      #BBOX: "8.25,46.97,9.58,47.52"
      #BBOX: "5.97,45.75,10.7,47.72"
      MIN_ZOOM: "0"
      MAX_ZOOM: "7"
